CarritowebG2/PresentacionAdmin/Controllers/MantenedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClaseEntidades;
using ClaseBDNegocio;
using System.IO;
using Newtonsoft.Json;
using System.Globalization;
using System.Configuration;

namespace PresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenedorController : Controller
    {
        private object configurationManager;

        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }

        // CATEGORIA

        #region CATEGORIA

        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> objLista = new List<Categoria>();

            objLista = new CN_Categoria().Listar();

            return Json(new { data = objLista }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GuardarCategoria(Categoria Objeto)
        {
            object resultado;
            string Mensaje = string.Empty;

            if (Objeto.cate_ID == 0) {

                resultado = new CN_Categoria().Registrar(Objeto, out Mensaje);
            }
            else {
                resultado = new CN_Categoria().Editar(Objeto, out Mensaje);
            }


            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int Cate_ID)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(Cate_ID, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion

        // MARCA

        #region MARCA

        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<Marca> objLista = new List<Marca>();

            objLista = new CN_Marca().Listar();

            return Json(new { data = objLista }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GuardarMarca(Marca Objeto)
        {
            object resultado;
            string Mensaje = string.Empty;

            if (Objeto.marc_ID == 0)
            {

                resultado = new CN_Marca().Registrar(Objeto, out Mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(Objeto, out Mensaje);
            }


            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarca(int marc_ID)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(marc_ID, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion
        
        // PRODUCTO

        #region Producto
        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> objLista = new List<Producto>();
            
            objLista = new CN_Producto().Listar();

            return Json(new { data = objLista }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GuardarProducto(string Objeto, HttpPostedFileBase archivoImagen)
        {
            object resultado;
            string Mensaje = string.Empty;
            bool operacionExitosa = true;
            bool GuardarImagenExito = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(Objeto);
            decimal Precio;

            if (decimal.TryParse(oProducto.prod_precioTexto,System.Globalization.NumberStyles.AllowDecimalPoint,new CultureInfo("es-AR"), out Precio))
            {

                oProducto.prod_Precio = Precio;

            }
            else
            {

                return Json(new { operacionExitosa = false, Mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);

            }
            if (oProducto.prod_ID == 0)
            {

                resultado = new CN_Producto().Registrar(oProducto, out Mensaje);
            }
            else
            {
                resultado = new CN_Producto().Editar(oProducto, out Mensaje);
            }

            if (oProducto.prod_ID == 0)
            {
                int idProductoGenerado = new CN_Producto().Registrar(oProducto, out Mensaje);

                if (idProductoGenerado != 0)
                {

                    oProducto.prod_ID = idProductoGenerado;

                }
                else
                {
                    operacionExitosa = false;
                }
            }
            else
            {

                operacionExitosa = new CN_Producto().Editar(oProducto, out Mensaje);

            }
            if (operacionExitosa == true)
            {

                if (archivoImagen != null)
                {

                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string prod_extension = Path.GetExtension(archivoImagen.FileName);
                    string nombre_imagen = string.Concat(oProducto.prod_ID.ToString(),prod_extension);


                    try
                    {

                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));

                    }
                    catch(Exception ex)
                    {

                        string msg = ex.Message;
                        GuardarImagenExito = false;

                    }

                    if (GuardarImagenExito == true)
                    {

                        oProducto.prod_RutaImagen = ruta_guardar;
                        oProducto.prod_NombreImagen = nombre_imagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out Mensaje);

                    }
                    else
                    {
                        Mensaje = "Se guardo el producto pero hubo un error con la imagen";

                    }


                }

            }

            return Json(new { prod_operacionExitosa = operacionExitosa, idGenerado = oProducto.prod_ID, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarProducto(int prod_ID)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(prod_ID, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult ImagenProducto(int prod_ID)
        {

            bool conversion = false;
            Producto oProducto = new CN_Producto().Listar().Where(p => p.prod_ID == prod_ID).FirstOrDefault();
            
            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.prod_RutaImagen, oProducto.prod_NombreImagen), out conversion);


            return Json(new
            {
                conversion = conversion,
                textoBase64 = textoBase64,
                extension = Path.GetExtension(oProducto.prod_Nombre)
            },
            JsonRequestBehavior.AllowGet
            );
        }



    }
    #endregion
}

CarritowebG2/PresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Carrito G2</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Configuraciones</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar sesion</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Resumen</div>
                            <a class="nav-link" href="@Url.Action("Index","Home")">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <a class="nav-link" href="@Url.Action("Usuarios", "Home")">
                                <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                                Usuarios
                            </a>
                            <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                            <a class="nav-link" href="@Url.Action("Categoria", "Mantenedor")">
                                <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                                Categoria
                            </a>
                            <a class="nav-link" href="@Url.Action("Marca", "Mantenedor")">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Marca
                            </a>
                            <a class="nav-link" href="@Url.Action("Producto", "Mantenedor")">
                                <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                                Producto
                            </a>

                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">

                        @RenderBody()

                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

    @* <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>